# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ian Hibbert
email: ian.hibbert.a@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Howdy doo fellas
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

github:
  username: ianhibbert
  repository_url: https://github.com/IanHibbert

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Include in Processing
include: ["_pages"]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

theme: jekyll-theme-slate